plugins { id 'com.android.application' }

android {
    namespace 'com.unisocsu.hosmim'
    compileSdk 35

    defaultConfig {
        applicationId 'com.unisocsu.hosmim'
        minSdk 19
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
