name: Package Repository

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: |
          git clone --depth 1 https://github.com/unisocsu/hosmim-o-mefanim.git source

      - name: Create ZIP
        run: |
          zip -r hosmim-o-mefanim.zip source

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hosmim-o-mefanim
          path: hosmim-o-mefanim.zip
          retention-days: 7
